import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SubLayout from './subLayout';
import ThemeContex from '../../../useContext/themeContext';
import '../../customer/customer.css';
import '../dashboard/notifications/notifications.css';
const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Dashboard-Flatcare Maintenance Planner',
  description:
    'Generated by create next appFlatCare, Maintenance Planning, Maintenance, Planning, Efficiency',
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SubLayout>
        <div className='dashboardChildren'>{children}</div>
      </SubLayout>
    </>
  );
}
