import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../dashboard/dashboard.css";
import CustomerHeader from "../header/CustomerHeader";

import CustomerDashboardNavigation from "./navigation/Navigation";
import Navigation from "./navigation/Navigation";
import Header from "../header/CustomerHeader";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <Header />
      <div className="layoutContainer">

        <section className="leftSide">
          <CustomerDashboardNavigation />
        </section>
        <section className='rightSide'>
          {children}
        </section>

      </div>
    </main>
  );
}
